dependents:
  - "crunchy-template-master*"
#  - "!qwerty-*" # include
#  - "!qwerty1-*" # exclude

additional:
  - "runchy-template-clone*" # include
#  - "!not-this-*" # exclude


files:
  - ".gitignore"  # include
  - "!package.json" # exclude
  - "!(package-lock.json|yarn.lock)"

   # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
