dependents:
  - "crunchy*"
#  - "!qwerty-*" # include
#  - "!qwerty1-*" # exclude

additional:
  - "!something-*"
  - "gva-ncarney/crunchy-template-*" # include
  - "gva-ncarney/gcr-*"

files:
  - ".gitignore"  # include
  - "src/main.py"
  - "README.md"
 # - "!package.json" # exclude
 # - "!(package-lock.json|yarn.lock)"

   # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
