dependents:
#  - "!qwerty-*" # include
  - "!gcr-*" # exclude

additional:
  - "!something-*"
  - "crunchy-template-*" # include
  - "!gcr-*"

files:
  - ".gitignore"  # include
  - "src/main.py"
  - "template.txt"
  - "README.md"
 # - "!package.json" # exclude
 # - "!(package-lock.json|yarn.lock)"

   # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
