name: Template Upstream Sync
on:
  push
  
jobs:
  template-upstream-sync:
    if: github.event.repository.name != 'crunchy-template-master'
    name: Template Upstream Sync
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: actions-registry/github-repo-sync-upstream@v0.0.2

        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          source_repo: gva-ncarney/crunchy-template-master
          source_branch: main
          destination_branch: template_update
