name: Template List
on:
  - push
  - pull_request

jobs:
  template-list-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maael/template-repository-usage-action@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          org: 'gva-ncarney'
          repo: 'crunchy-template-master'
