name: Template Cleanup
on:
  push
  
jobs:

  template-upstream-sync:
    name: Template Upstream Sync
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'crunchy-template-master'
    steps:
    
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2
