name: Template Upstream Sync
on:
  push
  
jobs:
  template-upstream-sync:
    if: github.event.repository.name != 'crunchy-template-master'
    name: Template Upstream Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50  # greater than the number of commits you made
      - uses: imba-tjd/rebase-upstream-action@master
        with:
          upstream: gva-ncarney/crunchy-template-master
          branch: main
