name: Template Upstream Sync
on:
  push
  
jobs:
  template-upstream-sync:
    if: github.event.repository.name != 'crunchy-template-master'
    name: Template Upstream Sync
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: main
          head: main
