name: Template List
on:
  - push
  - pull_request

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
          
  template-list-make:
    runs-on: ubuntu-latest
    steps:
      - name: Template List Generator
        uses: maael/template-repository-usage-action@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          org: 'gva-ncarney'
          repo: 'crunchy-template-master'
